# config/credentials.yml.example
databases:
  source_db:
    username: ${SOURCE_DB_USER}
    password: ${SOURCE_DB_PASSWORD}
  quality_db:
    username: ${QUALITY_DB_USER}
    password: ${QUALITY_DB_PASSWORD}